#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Coldpaper

# Short bio or description (displayed in the header)
description: coldpaper.me

#
# Flags below are optional
#

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/Coldbell4869/coldbell4869.github.io/master/favicon.ico


# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'zTheme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: Coldbell
    url: /coldbell
#   - name: Blog
#     url: /
  - name: Tags
    url: /tags
  - name: Archive
    url: /archive
  - name: Instagram
    url: https://www.instagram.com/coldbellgram/?hl=ko
#   - name: Facebook
#     url: https://facebook.com/coldbell
#   - name: Naver
#     url: https://naver.com
#   - name: GA
#     url: https://datastudio.google.com/open/1Bd3S6KJ5QQ5C11nkcgdhhbEs1M6zxWZk

# Pagination
paginate: 5

# Includes an icon in the footer for each username you enter
footer-links:
  behance: # https://www.behance.net/<username>
  dribbble:
  email: coldbell4869@gmail.com
  facebook: coldbell
  flickr:
  github: Coldbell4869
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram: coldbellgram
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  twitter: 
  youtube: # channel/<your_long_string> or user/<user-name>

# Text under the icons in footer
footer-text: Â© 2019 Coldpaper, Coldbell

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: coldpaper

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Or enter your Google Tag Manager web tracking code https://tagmanager.google.com (e.g. GTM-5RRMLA) to activate tracking
google_tag:
  ua: GTM-P7RHDCP

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
